### ISSUE TITLE
[Add Resources] Add C# IDEs specific to .NET developers

### ISSUE THREAD

**Issue by davecodesbug** [Timonwa/techroadmap#112]
### Task

The C# section of the backend roadmap is missing well-rounded and suitable IDE for .NET devs. It will be good to add this in order for beginners to not have a hard time choosing the best IDE for themselves.

**Comment by Timonwa** [comment]
Please add the IDE in the [Desktop section for Code Editors](https://www.techroadmap.xyz/careers/backend#desktop-apps). Also, could you add links to the website, documentation, and one or two tutorial video on how to use it?

Also, could you indicate in the title that it is for C# users? eg, Rider (for C# and .NET), and follow the right pattern.

**Comment by davecodesbug** [comment]
Will do, update you soonest as I'm done.
