### ISSUE TITLE
Fix accessibility issues on the site

### ISSUE THREAD

**Issue by winniebosy** [Timonwa/techroadmap#113]
**Describe the bug**
-Some of the links do not contain accessible texts to describe purpose or functionality.
- Low color contrast on link elements
- Redundant links amongst many other issues

**To Reproduce**

1. Go to wave and run the test tool
2. See error

**Expected behavior**
- Accessible names that describe the purpose so that people using assistive technologies can understand the content.
- Users with low vision can interact with the links at ease.

**Screenshots**
![A screenshot of a sample of  accessibility issues on the website](https://user-images.githubusercontent.com/40880690/215182510-a2abacbb-73e9-4905-a160-942fe343fabf.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version :109

##Kindly assign me these issues for fixing.Thanks

**Comment by Timonwa** [comment]
Hi @winniebosy, can you drop a link to the wave too?

**Comment by winniebosy** [comment]
Sure. https://wave.webaim.org/extension/

**Comment by Timonwa** [comment]
ok. you can fix the errors. For the Low color contrast, Change one of them to pink and the other to green (use the colors already available), then add a screenshot here, let me see which one I prefer.
