### ISSUE TITLE
Update SideHustle.ng internship link and name

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#124]
## Task
- In the Networking section for both Frontend and Backend track, in the Internships and Mentoring part, SideHustle.ng has rebranded. Update the link and name.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by FardeenCODEIIEST** [comment]
Hey @Timonwa , can you please assign me this task, I think I can do it.

**Comment by Timonwa** [comment]
Hi @FardeenCODEIIEST. I appreciate your interest in this issue. Yes. You can go ahead with it. Please don't forget to give us a star.

**Comment by FardeenCODEIIEST** [comment]
Sure @Timonwa , thanks
