### ISSUE TITLE
Add more Tech communities to the Networking section in the Frontend/Backend Track

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#125]
Please follow the format in the code.
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by Luckydhingra** [comment]
hey i would like to work on it 
would u assign me this one :)

**Comment by Timonwa** [comment]
Sure. Go ahead @Luckydhingra . Please give us a star if you haven't already.
