### ISSUE TITLE
Add more Bootcamps to to the Networking section in the Frontend/Backend Track

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#126]
Please follow the format in the code.
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by codewithfan** [comment]
Would love to tackle this one! May I be assigned?

**Comment by Timonwa** [comment]
feel free to work on this @codewithfan

**Comment by stefanintech** [comment]
Still will work on the issue! 👍🏾

**Comment by Timonwa** [comment]
no problem @stefanintech
