### ISSUE TITLE
Add relevant articles on Html and CSS to the Html and Css (Beginner's Level) section in the Frontend Track

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#128]
## Task
- add relevant articles in this section that discuss a concept or particular topic. For example in the API section, you can add an article to the article list on 'Promises in JavaScript' or 'Knowing the difference between var, let and const' in the JavaScript section article list.

## Things to Note
- add only articles that are relevant and useful to frontend development.
- be as descriptive as possible when naming your links and do not forget to include the author or creator of the content.
Eg. 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- confirm that the article has not already been added.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by Saloni0512** [comment]
Hey @Timonwa I would like to work on this issue.

**Comment by Saloni0512** [comment]
Hey can you assign me this issue so that I can start working on it

**Comment by Timonwa** [comment]
Sure, @Saloni0512, you can go ahead with this. Please give us a star if you haven't already. 😁
