### ISSUE TITLE
Add relevant resources on Html and CSS to the Html and Css (Beginner's Level) section in the Frontend Track

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#129]
## Add Relevant Links
Under the Html and Css (Beginner's Level) section in the [frontend development page](https://techroadmap.xyz/frontend), the `Others` category is missing relevant links on dev tools, tricks, chrome extensions, etc.

## Task
- Add relevant links about useful dev tools, chrome extensions, tricks, or cool ways or examples to use the tools or languages in each section's `others` category.
- Please be sure to be detailed when naming the links and include the name of the author of the article, video, or website. eg 'Top 10 chrome extensions for frontend development. ~ John Doe [Article]' or '[CSS code examples ~ FreeFrontend](https://freefrontend.com/css-code-examples/) [Link]'
- Always attach the name of the author.
- Confirm that the link has not already been added.
- Please follow the code format or template used.
- Always attach a badge to the links. Examples of badges are: Video, Playlist, Article, Link, Documentation, Website, etc.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by Manikantan-S** [comment]
@Timonwa I can work on this issue ,Please assign this to me under hacktoberfest.Thanks !!

**Comment by Timonwa** [comment]
Sure. You can go ahead to work on this @Manikantan-S . Please give us a star if you haven't already. 🥰

**Comment by Manikantan-S** [comment]
Thanks a lot !!

**Comment by Manikantan-S** [comment]
I have created a pull request for this issue the link to the pr is 
https://github.com/Timonwa/techroadmap/pull/153

**Comment by Manikantan-S** [comment]
I 've created a pr for this issue the link to my pr is #155

**Comment by Manikantan-S** [comment]
Can you please close this issue @Timonwa as my pr has been merged and it gets notified in hacktoberfest.Thanks !!

**Comment by Timonwa** [comment]
Hi @Manikantan-S . I have added the Hacktoberfest accepted badge to your PR. So, It will be accepted by Hacktobefest. But I have to rearrange the links before I merge your PR.

**Comment by Manikantan-S** [comment]
Oh ok .Thanks a lot  Timonwa!!

**Comment by Manikantan-S** [comment]
Oh ok .Thanks a lot  Timonwa!!
