### ISSUE TITLE
[Add Resources] Add relevant frontend articles to the sections in the frontend development page.

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#13]
# Add Relevant Articles
The following sections in the [frontend development page](https://techroadmap.xyz/html/careers/frontend.html) are missing articles related to that section.

## Sections
- Html and CSS (Beginner's Level)
- Html and CSS (Advanced Level)
- JavaScript
- JavaScript (Advanced)
- Json

## Task
- add relevant articles that discusses about a concept or particular topic in that section. For example in the API section, you can add an article to the article list on 'Promises in JavaScript' or 'Knowing the difference between var, let and const' in the JavaScript section article list.

## Things to Note
- add only articles that are relevant and useful to frontend development.
- be as descriptive as possible when naming your links and do not forget to include the author or creator of the content.
Eg. 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- confirm that the article has not already been added.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by fahdarafat** [comment]
Can I work on this?

**Comment by Timonwa** [comment]
Yes, you can

**Comment by Timonwa** [comment]
> Can I work on this?

Yes @fahdarafat . You can.

**Comment by roshni-salpekar** [comment]
I would like to contribute. Can I work on this?

**Comment by Timonwa** [comment]
> I would like to contribute. Can I work on this?

Yes @roshni-salpekar , you can go ahead.

**Comment by shashanksjSSJ** [comment]
Hello @Timonwa, can I add [this](https://css-tricks.com/snippets/css/complete-guide-grid/) article for grids and [this](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) article for flexbox under Advanced HTML/CSS, this would be a great way to learn how to contribute to open source. 
Thank You

**Comment by Timonwa** [comment]
Yes, @shashanksjSSJ, you can go ahead and add those links.
