### ISSUE TITLE
Add relevant articles on Javascript to the Javascript section in the Frontend Track

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#131]
## Task
- add relevant articles in this section that discuss a concept or particular topic. For example, in the API section, you can add an article to the article list on 'Promises in JavaScript' or 'Knowing the difference between var, let and const' in the JavaScript section article list.

## Things to Note
- add only articles that are relevant and useful to front-end development.
- be as descriptive as possible when naming your links, and do not forget to include the author or creator of the content.
E.g., 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- confirm that the article has not already been added.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by grvzm** [comment]
I want to add a few on the following topics:
- Object Destructuring
- When and why use Arrow functions
- Spread & Rest Operators
- Promises & Async Programming
Assign me pls.

**Comment by Timonwa** [comment]
Hi @grvzm , please go ahead. please give us a star if you haven't already.

**Comment by grvzm** [comment]
@Timonwa I forgot to link this issue #150  , can you do that?
