### ISSUE TITLE
Add relevant resources to the Javascript Advanced section in the Frontend Track

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#134]
## Add Relevant Links
Under the Javascript Advanced section in the [frontend development page](https://techroadmap.xyz/frontend), the `Others` category is missing relevant links on dev tools, tricks, chrome extensions, etc.

## Task
- Add relevant links about useful dev tools, chrome extensions, tricks, or cool ways or examples to use the tools or languages in the `others` category.
- Please be sure to be detailed when naming the links and include the name of the author of the article, video, or website. eg 'Top 10 chrome extensions for frontend development. ~ John Doe [Article]' or '[CSS code examples ~ FreeFrontend](https://freefrontend.com/css-code-examples/) [Link]'
- Always attach the name of the author.
- Confirm that the link has not already been added.
- Please follow the code format or template used.
- Always attach a badge to the links. Examples of badges are: Video, Playlist, Article, Link, Documentation, Website, etc.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by KaushikKundu** [comment]
Can I take this issue? @Timonwa
