### ISSUE TITLE
Add relevant articles to the Javascript Advanced section in the Frontend Track 

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#135]
## Task
- add relevant articles in this section that discuss a concept or particular topic. For example, in the API section, you can add an article to the article list on 'Promises in JavaScript' or 'Knowing the difference between var, let and const' in the JavaScript section article list.

## Things to Note
- add only articles that are relevant and useful to front-end development.
- be as descriptive as possible when naming your links, and do not forget to include the author or creator of the content.
E.g., 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- confirm that the article has not already been added.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by ATREAY** [comment]
hey @Timonwa, can I work on this issue?

**Comment by Timonwa** [comment]
yes @ATREAY. go ahead.

**Comment by ATREAY** [comment]
Hey @Timonwa, I've made the necessary changes. Could you please take a look?

**Comment by ATREAY** [comment]
Hey @Timonwa, could you please take a look at this PR? I've added some relevant articles on advanced JavaScript concepts.

**Comment by grvzm** [comment]
Hey @ATREAY , one of the Articles that you are adding "var, let and const - what's the difference" is already there in the Javascript section, see before the Javascript Advanced, in the Frontend Track.

**Comment by ATREAY** [comment]
Sure, @grvzm, in that case, I'll add another one instead. Thanks for letting me know.

**Comment by ATREAY** [comment]
Hey @grvzm and @Timonwa, could you please take a look at it now and let me know if any changes are needed?
