### ISSUE TITLE
Add relevant frontend articles on APIs

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#138]
## Task
- On the Front-end Dev page, add relevant front-end development articles in the API section that talk about APIs. E.g., how to use it, understand it, etc.

## Things to Note
- add only articles that are relevant and useful to front-end development.
- be as descriptive as possible when naming your links, and do not forget to include the author or creator of the content.
E.g., 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by Shivam36998** [comment]
@Timonwa can you please assign this to me?

**Comment by Timonwa** [comment]
Hi @Shivam36998, I have assigned it to you. Please don't forget to give this repo a star. 😄

**Comment by Shivam36998** [comment]
thank you very much @Timonwa, i will be updating it soon

**Comment by Timonwa** [comment]
Hi @Shivam36998 , any update on this?

**Comment by Shivam36998** [comment]
i am really sorry @Timonwa, your website supports a great cause and i really don't intend to make it late, but i got stuck in my university exams, although i am in midway of it. Believe in me a little bit more i will be updating it soon

**Comment by Timonwa** [comment]
Oh. No problem about it. @Shivam36998. I Wish you the best in your exams.

**Comment by Shivam36998** [comment]
@Timonwa i have made a pull request few days back, did you check it ?
