### ISSUE TITLE
Add 1 or 2 more video playlists on APIs in Frontend Development

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#139]
## Task
- On the Front-end Dev page, add relevant front-end development playlists, preferably from YouTube, that are about APIs.

## Things to Note
- add only links that are relevant and useful to front-end development.
- be as descriptive as possible when naming your links, and do not forget to include the author or creator of the content.
E.g., 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by adarshpathak3408** [comment]
Please assign this issue to me with the "Hacktober Fest" label

**Comment by Timonwa** [comment]
Hi @adarshpathak3408, thank you for your interest in this. Please give us a star if you haven't yet. 😄

**Comment by Timonwa** [comment]
Hi @adarshpathak3408, any update on this?

**Comment by Drex72** [comment]
Sorry @Timonwa ,Has this issue been resolved, i would like to work on this

**Comment by Timonwa** [comment]
Nope, @Drex72, it is still open.

**Comment by Drex72** [comment]
Alright
i'd get started on it

**Comment by Drex72** [comment]
Alright
i'd get started on it
