### ISSUE TITLE
Link to GitHub website and other version controls are missing.

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#14]
# Add website/download/documentation link.

On the frontend development career page, there is a section called [Version Control](https://techroadmap.netlify.app/html/careers/frontend.html#version-control). For each list, the links to their website, documentation and download link if applicable are missing.

## List
- [x] Git
- [x] Git Desktop
- [x] GitHub
- [x] GitLab
- [x] Bitbucket

## Task
For the above list,
- add link to the website of the service with the name of the link saved as "Website".
- add link to the documentations page of the service with the name of the link saved as "Documentation".
- add link to the download page of the service if applicable with the name of the link saved as "Download here".
- include a badge for each link, with the label of the badge set to 'Link'. (view examples of the badge on the links in this section.)

- ## Things to Note
- the website link must come first,
- the download link must come second,
- and the documentations page link must come third on the list.
- please follow the code format/template on the html page.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#readme#getting-started) to this repository.

**Comment by aryancharan** [comment]
can i work on this problem

**Comment by Timonwa** [comment]
Yes @aryancharan. You can work on it.

**Comment by mohit1607** [comment]
I am willing to work on it

**Comment by Timonwa** [comment]
> I am willing to work on it Can I work on it ?
@mohit1607 you can go ahead with this.

**Comment by mohit1607** [comment]
Just a one problem I made the  changes in my computer and the local repo is  up to date but when I type command 
"git push origin <branch-name>" I get this :  remote: Permission to Timonwa/techroadmap.git denied to mohit1607.
fatal: unable to access 'https://github.com/Timonwa/techroadmap.git/': The requested URL returned error: 403

**Comment by Timonwa** [comment]
I think you are trying to push directly to the main repo instead of you own repo. It's not possible to do that since you don't have access to the main repo.
Try doing that first. Or just do git push, it should show you  something like git push --set-upstream origin branch.. Then you copy and paste it.
