### ISSUE TITLE
Add articles on Java to the Backend Dev Page

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#141]
## Task
- add relevant articles on Java on the backend page.

## Things to Note
- add only articles that are relevant and useful to backend development.
- be as descriptive as possible when naming your links, and do not forget to include the author or creator of the content.
E.g., 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by Mayank77maruti** [comment]
Hey @Timonwa  , I would like to contribute to your project under hacktoberfest, kindly assign this issue to me,
Thanks for your consideration!

**Comment by Mayank77maruti** [comment]
Hey @HimanshuNarware , I would like to contribute to your project , kindly assign this issue to me,
Thanks for your consideration!

**Comment by Mayank77maruti** [comment]
Hey @Timonwa , I would like to contribute to this project , kindly assign this issue to me,
Thanks for your consideration!
