### ISSUE TITLE
Add articles on C++ to the Backend Dev Pag

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#142]
## Task
- add relevant articles on C++ on the backend page.

## Things to Note
- add only articles that are relevant and useful to backend development.
- be as descriptive as possible when naming your links, and do not forget to include the author or creator of the content.
E.g., 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by Shaurya10101** [comment]
Please assign me this issue under HacktoberFest

**Comment by Manikantan-S** [comment]
@Timonwa Can you please assign this issue to me .I would love to work on it ,Can you please assign this to me under Hacktoberfest

**Comment by Manikantan-S** [comment]
I have pr to this. The link to pr is #156
