### ISSUE TITLE
Add articles on C language to the Backend Dev Page

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#143]
## Task
- add relevant articles on C language in the backend page.

## Things to Note
- add only articles that are relevant and useful to backend development.
- be as descriptive as possible when naming your links, and do not forget to include the author or creator of the content.
E.g., 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- follow the code format or template used.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by Shaurya10101** [comment]
Please assign me this issue under HacktoberFest

**Comment by Manikantan-S** [comment]
@Timonwa Please assign this to me under hacktoberfest .Thanks !!

**Comment by Timonwa** [comment]
@Manikantan-S, do you still want to work on this?

**Comment by Manikantan-S** [comment]
I'm sorry I can't as I have my exams going on

**Comment by Timonwa** [comment]
no probem. thank you for your other contributions. 🫂

**Comment by Saloni0512** [comment]
Hey @Timonwa I would like to take up this issue. Can you assign to me

**Comment by Timonwa** [comment]
Yes. i have assigned it to you. @Saloni0512
