### ISSUE TITLE
[Add Resources] Add relevant links on tools, tricks, etc to the backend languages in the backend development page.

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#15]
# Add Relevant Links
The following languages in the [backend development page](https://techroadmap.xyz/backend) are missing resources on tools, tricks, chrome extensions, etc.

## Sections
- Node.js
- Python
- C

## Task
- Add relevant links about useful dev tools, chrome extensions, tricks, or cool ways or examples to use the tools or languages in each section's `others` category.
- Please be sure to be detailed when naming the links and include the name of the author of the article, video, or website. eg 'Top 10 chrome extensions for backend development. ~ John Doe [Article]' or '[CSS code examples ~ FreeFrontend](https://freefrontend.com/css-code-examples/) [Link]'
- Always attach the name of the author.
- Confirm that the link has not already been added.
- Please follow the code format or template used.
- Always attach a badge to the links. Examples of badges are: Video, Playlist, Article, Link, Documentation, Website, etc.

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by siuting0511** [comment]
Hi, I would be interested to work on this, can I be assigned to work on this?

**Comment by Timonwa** [comment]
> Hi, I would be interested to work on this, can I be assigned?

Yes @siuting0511, you can go ahead with this issue

**Comment by pritipsingh** [comment]
Hey @Timonwa the link you've added for the front end page seems to be broken? But I've been working with Javascript for quite some time. And would love to take this up.

**Comment by Timonwa** [comment]
Thank you. I have fixed it. I changed the domain name and forgot to update it in the issues. I'm currently moving all the code to react. I'm almost with it, how would you like to contribute or what issue do you want to take up.

**Comment by pritipsingh** [comment]
I could help you with documentation of the frontend and blockchain as well as with moving the codebase to React. Lemme know how to go about it?

**Comment by Timonwa** [comment]
I am done with moving it to React. there are some open issues for the frontend page and I will soon open issues for the backend page as well.
Someone is already working on the roadmap for the blockchain.

What type of documentation do you have in mind?

**Comment by pritipsingh** [comment]
Hey Timonwa! I had a look at it and I believe since I am new here, it would be better for me to know what do you have on your mind? I'll act accordingly and maybe then add my fresh perspective later on!  I'll wait for you to open issues and try to solve that. Thank you!

**Comment by Timonwa** [comment]
No problem.

**Comment by Timonwa** [comment]
Hi @pritipsingh. I have opened some issues for the backend, do check if there are some you can work on .

**Comment by pritipsingh** [comment]
Hey @Timonwa I am currently busy with my end semester exams for the next 12 days. I'll definitely get involved after 10 days. Thank you for your response.

**Comment by Timonwa** [comment]
no problem  @pritipsingh

**Comment by pritipsingh** [comment]
Hey, @Timonwa Do you have something for me I could work on?

**Comment by anthonychinwe** [comment]
Hello @Timonwa, I would like to add a tutorial article for this issue.

**Comment by Timonwa** [comment]
Hi @pritipsingh, I have opened a few CSS-related issues if you are interested in them. You can check them out.

**Comment by pritipsingh** [comment]
yes sure :)

**Comment by Tonie-NG** [comment]
Hey @Timonwa . Is this issue still open?

**Comment by Timonwa** [comment]
Yes it is. @Tonie-NG. feel free to add relevant links where applicable.

**Comment by codewithfan** [comment]
Hi @Timonwa, I would love to add another link to the JavaScript framework, React section! Scrimba and a course from Frontend Masters, Intro to React v8.

**Comment by Drex72** [comment]
Hey @Timonwa ,is there an issue, or rather does this issue still exist?i if it does, i would like to work on it, if not, i'd love to work on backend related issues

**Comment by Timonwa** [comment]
hi @Drex72 , the issue is still open for the languages
- Node.js
- Python
- C

**Comment by Drex72** [comment]
Oh
alright
i'd take for Nodejs
Does that work?

**Comment by Timonwa** [comment]
yes. sure
