### ISSUE TITLE
Add video or article on how to use BitBucket.

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#16]
On the frontend development career page, there is a section called [Version Control](https://techroadmap.netlify.app/html/careers/frontend.html#version-control). One of the list called BitBucket is missing links to articles or videos how how to use it.

## Task
- add a maximum of 2 relevant videos on how to use BitBucket.
- add a maximum of 2 relevant articles on how to use BitBucket.

## Things to note:
- only add videos or articles that are relevant and useful.
- please be as descriptive as possible when naming your links and do not forget to include the author or creator of the content.
Eg. "21 no-code tech jobs you can do to become a tech sis or tech bro. ~ Timonwa"

## Resources
View how to [contribute](https://github.com/Timonwa/techroadmap#getting-started) to this repository.

**Comment by ipeavy** [comment]
Hey, Can I be assigned to this issue?

**Comment by Timonwa** [comment]
Yes, you can go ahead with this issue.

**Comment by ipeavy** [comment]
Sorry for the delay, Can I push changes?

**Comment by Timonwa** [comment]
Yes you can, the issue is still open.

**Comment by anant-strong** [comment]
@Timonwa  I have created a pull request. Can you please review it?
