### ISSUE TITLE
[Roadmap] Add Blockchain Developer Roadmap

### ISSUE THREAD

**Issue by Tusharjagi** [Timonwa/techroadmap#42]
**I Visit your website and found there is No roadmap of blockchain developer**

**I think blockchain developers very popular and attactive career path**

I am new in opensource, I know the Roadmap of **Blockchain Developer** , 
So can i contribute in your project .

**Comment by Timonwa** [comment]
Yes. We don't have that yet. We are currently working on the backend development and technical writing roadmap. Once we have those pages up and running, our next roadmap is blockchain development. You can drop your email if you want to be notified when we start working on that.

In the meantime, if you want to create the blochchain roadmap from scratch for us, you can send us an email at [techcareerroadmap@gmail.com](mailto:techcareerroadmap@gmail.com), on how you would go about it, and we could collaborate on it with you. Thank you.

**Comment by Tusharjagi** [comment]
Yeah Sure, 
I have doubt -> Creating blockchain roadmap form scratch means that 
                           I would to Create a WebPage blockchain road map for your website, Similar to Fronted Development Roadmap 
                           WebPage .

**Comment by Timonwa** [comment]
What I meant was, do you want to create the step by step guide on how to become a Blockchain developer and also add the resources by yourself.
Or you just want to add the resources after when we create the step by step guide by ourselves.

**Comment by Tusharjagi** [comment]
Okay sure

**Comment by Tusharjagi** [comment]
Hey @Timonwa ,
When can i add links ???

**Comment by Timonwa** [comment]
Hi @Tusharjagi , sorry for the delay, you can work on it now. Just make sure that you pull from the NewRoadmapBranch. I have created a page for it and also a few components for the blockchain roadmap, which you can only find on that particular branch. Please let me know if you need any help or assistance. Thank you.

**Comment by pritipsingh** [comment]
Hey! I am a blockchain Developer myself. Do you mind if I take up this issue if it's still on?

**Comment by Timonwa** [comment]
Hi @pritipsingh, sorry for the late reply. Yes, the issue is still open, and you are free to work on it if you are still interested. Could you tell me how you would like to go about creating the roadmap?
