### ISSUE TITLE
[Roadmap] Adding Machine Learning roadmap

### ISSUE THREAD

**Issue by vedantpople4** [Timonwa/techroadmap#43]
I would like to add Machine Learning Roadmap to this project.

**Comment by Timonwa** [comment]
Hi @vedantpople4, can you kindly send an email to [techcareerroadmap@gmail.com](mailto:techcareerroadmap@gmail.com) giving and outline and summary/details of the machine learning roadmap.

**Comment by golu098** [comment]
Hi @vedantpople4 can you kindly send an email to (shivkantkr9934@gmail.com) or mention here giving the outline and summary/details of the machine learning roadmap.
