### ISSUE TITLE
[FEATURE] Add more Backend Languages and resources 

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#54]
# Add more Backend Languages

Currently, there are only 2 languages added in the [backend roadmap's page](https://techroadmap.xyz/backend). More needs to be added.

## Languages to be added

- [ ] PHP
- [x] Java
- [x] C#
- [ ] Ruby
- [x] C++
- [x] C
- [x] Go
- [ ] .NET

## Task
- create sections for each languages in the [BackendLangs.js file](BackendLangs.js) .
- add relevant resources to the subsections for each languages.

## Things to Note

- Read our  [contributing guidelines](https://github.com/Timonwa/techroadmap#getting-started) before making your contribution.
- only one language per person per pull request.
- if you don't have resources to all the subsections in the language section that is fine, add the ones you know. 
- be as descriptive as possible when naming your links and do not forget to include the author or creator of the content.
Eg. 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- do not duplicate resources or sections.
- follow the code format or template used.
- include the link to the section in the [Backend sidebar component](https://github.com/Timonwa/techroadmap/blob/main/src/components/backendPageContent/BackendNav.js) file.

**Comment by Goutham-erram** [comment]
Yep, I will add one language per pull request and , I will start with C programming language

**Comment by Timonwa** [comment]
That sounds great. Thank you @Goutham-erram
