### ISSUE TITLE
[FEATURE] Add more Backend Frameworks

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#55]
# Add more Backend Languages Framework

Currently, there are only 3 backend frameworks added in the [backend roadmap's page](https://techroadmap.xyz/backend). More needs to be added.

## Frameworks to be added
- [ ] Koa
- [ ] Laravel
- [ ] Slim
- [ ] ASP.NET
- [ ] and ASP.NET Core
- [ ] Gin
- [ ] GORM
- [ ] Spring
- [ ] Spring Boot
- [ ] Rust and Rocket
- [ ] .NET Core
- [ ] .NET Framework.

## Task
- create sections for each frameworks in the [Frameworks.js file]( https://github.com/Timonwa/techroadmap/blob/main/src/components/backendPageContent/Frameworks.js) .
- add relevant resources for each frameworks.

## Things to Note

- Read our  [contributing guidelines](https://github.com/Timonwa/techroadmap#getting-started) before making your contribution.
- only one language per person per pull request.
- be as descriptive as possible when naming your links and do not forget to include the author or creator of the content.
Eg. 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- do not duplicate resources or sections.
- follow the code format or template used.
- include the link to the section in the [Backend sidebar component](https://github.com/Timonwa/techroadmap/blob/main/src/components/backendPageContent/BackendNav.js) file.

**Comment by lumenCodes** [comment]
Hello @Timonwa do we tweet about this so people can know about it and possibly contribute.

**Comment by Timonwa** [comment]
Yes we can. I have been thinking about shceduling tweets to post automatically using a scheduling tool, but I wanted to add more issues first.

**Comment by shashanksjSSJ** [comment]
Hello, I am a newbie to Open Source, if this issue is still open can I add a framework, this would be a great way to learn for me

**Comment by shashanksjSSJ** [comment]
Can I add Django Franework

**Comment by Timonwa** [comment]
It has been added already. The ones yet to be added are listed in the issue.
