### ISSUE TITLE
[FEATURE] Add more Database Languages

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#56]
# Add more Database Languages

The [database section](https://www.techroadmap.xyz/backend#databases) in the backend roadmap page is divided into two; Relational and Non-Relational. Currently only one language is present for each.

## Languages to be added
- Relational Database
    - [x] PostgreSQL
    - [x] Microsoft SQL Server
    - [x] Oracle
    - [x] SQLite
    - [x] MariaDB

- Non-Relational Database
    - [x] CouchDB
    - [x] Firestore

## Task
- create sections for each languages in the [Database.js file]( https://github.com/Timonwa/techroadmap/blob/main/src/components/backendPageContent/Database.js) .
- add relevant resources for each frameworks.

## Things to Note

- Read our  [contributing guidelines](https://github.com/Timonwa/techroadmap#getting-started) before making your contribution.
- only one language per person per pull request.
- be as descriptive as possible when naming your links and do not forget to include the author or creator of the content.
Eg. 'Build a food recipe app with fetch API and vanilla JavaScript. ~ GeetProbin'.
- do not duplicate resources or sections.
- follow the code format or template used.
- include the link to the section in the [Backend sidebar component](https://github.com/Timonwa/techroadmap/blob/main/src/components/backendPageContent/BackendNav.js) file.

**Comment by sanzous** [comment]
Hello wanted to contribute to the project! Love what the website is for and the help it'll provide countless people.

**Comment by Joeyg61703** [comment]
Hello! interested in helping with Microsoft SQL Server.

**Comment by Timonwa** [comment]
> Hello wanted to contribute to the project! Love what the website is for and the help it'll provide countless people.

Thank you @sanzous. It means a lot to me.

**Comment by Timonwa** [comment]
> Hello! interested in helping with Microsoft SQL Server.

Please go ahead with it. @Joeyg61703

**Comment by HondaChan14** [comment]
Hey Timonwa. I wanna help contribute to Oracle!

**Comment by Ash9311** [comment]
Hi I would like to take this enhancement

**Comment by Timonwa** [comment]
Hi @Ash9311, welcome. You can pick a language that has not been added yet and work on that.

**Comment by Ash9311** [comment]
Hi @Timonwa , i have added SQLite and sent review request for the same. please check from your end.

**Comment by Timonwa** [comment]
Hi @Ash9311 . Sorry for the last response. I will review it soon.

**Comment by MehmetTerc** [comment]
Can i get mariaDB ?

**Comment by Timonwa** [comment]
hi @MehmetTerc, thank you for your interest in this issue. Please ensure that the links you add are relevant to mariaDB and that the resources are not outdated
