### ISSUE TITLE
[STYLING]

### ISSUE THREAD

**Issue by benjaminsanga** [Timonwa/techroadmap#66]
The mouse pointer does not change for some links like the Table of content, and the scroll bar is hard to see

A better styling for mouse hovers on links and buttons and styling for the scroll bar.

Change/add properties for when links are hovered on like a color shade or change the pointer, and give the vertical scroll bar a different color.

The links on the navbar may use better styling, links like Table of content need an indication to show they are links not just texts, scroll bar needs a distinction to be noticeable.

**Comment by Timonwa** [comment]
Thank you @benjaminsanga for raising this issue. Would you like to work on this for us?

**Comment by benjaminsanga** [comment]
Yes, sure
