### ISSUE TITLE
[BUG] One of the Backend Mobile App listed is not properly styled.

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#75]
**Describe the bug**
In the **Code Editors** section on the **Backend career page**, one of the apps listed in the **Mobile apps** subsection, **Code Editor** is styled as a subheading instead of a listed item.

**To Reproduce**
You can go to the Backend career page, scroll to the Code Editor section, then the Mobile App subsection or view it here: https://www.techroadmap.xyz/careers/backend#mobile-apps.

**Expected behaviour**
The Code Editor should have the same styling as the Dcoder or Visual Code.

**Screenshots**
![FireShot Capture 010 - Backend Development Roadmap  - Tech Roadmap  - www techroadmap xyz](https://user-images.githubusercontent.com/63044364/188308587-fcb13a8d-60ac-4529-a045-784683d42b6e.png)

**Comment by Roxie2003** [comment]
I would like to work on this Assignment..

**Comment by Timonwa** [comment]
You can go ahead @Roxie2003. Please give us a star if you haven't already. 😄
