### ISSUE TITLE
[Bug] Tools Badge not properly styled in Html and CSS Advanced section in Frontend Page.

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#76]
**Describe the bug**
The Tools badge is not styled correctly in the Others subsection in Html and CSS Advanced section on the Frontend Page. https://www.techroadmap.xyz/careers/frontend#css-advanced

**Screenshots**
It looks like this:
![FireShot Capture 011 - Frontend Development Roadmap  - Tech Roadmap  - www techroadmap xyz](https://user-images.githubusercontent.com/63044364/188309294-8c5040f5-f7d9-45de-b5b0-bb22d86d2539.png)

It should look like this:
![FireShot Capture 012 - Frontend Development Roadmap  - Tech Roadmap  - www techroadmap xyz](https://user-images.githubusercontent.com/63044364/188309298-ac561cfa-e2cd-4977-b0cc-a9e0833d93d7.png)

**Comment by Roxie2003** [comment]
I would like to work on this assignment
