### ISSUE TITLE
[FEATURE] Add Hover state on the Side bar links

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#80]
**Is your feature request related to a problem? Please describe.**
When a user hovers over any of the links in the side menu on the careers page, there is no hover effect on the link.

**Describe the solution you'd like**
A hover effect should be on the link in the sidebar menu on the careers page. For example, the colour changes to a lighter colour, the links move slightly to the left or right, etc.

**Additional context**
Please tell us how you would like to style this hover state before making the changes.

**Comment by Ash9311** [comment]
Assign it to me i can do this

**Comment by Timonwa** [comment]
Ok, @Ash9311. Also, star our repo if you haven't yet.

**Comment by Ash9311** [comment]
![image](https://user-images.githubusercontent.com/44554225/189497602-adb5b85c-78c1-45d1-9db5-6698769070a1.png)
added a slightly light hover effect on hover of link in sideBar menu
